# Generated by Django 3.2 on 2022-04-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='YearTime',
        ),
        migrations.RenameField(
            model_name='type',
            old_name='category',
            new_name='year_time',
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.CharField(choices=[('1-4 лет', 'One Four'), ('4-8 лет', 'Four Eight'), ('8-13 лет', 'Eight Thirteen')], max_length=10),
        ),
    ]
