# Generated by Django 3.2 on 2022-04-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Названия типа одежды')),
                ('year_time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='shop.yeartime', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип одежды',
                'verbose_name_plural': 'Типы одежды',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('available', models.BooleanField(default=True, verbose_name='актуальность')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('stock', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('gender', models.CharField(choices=[('Мальчик', 'Male'), ('Девочка', 'Female')], max_length=10)),
                ('year', models.CharField(choices=[('0-1 года', '0-1 года'), ('1-2 года', '1-2 года'), ('2-3 года', '2-3 года'), ('3-4 года', '3-4 года'), ('4-5 лет', '4-5 лет'), ('5-6 лет', '5-6 лет'), ('6-7 лет', '6-7 лет'), ('7-8 лет', '7-8 лет'), ('8-9 лет', '8-9 лет'), ('9-10 лет', '9-10 лет'), ('10-11 лет', '10-11 лет'), ('11-12 лет', '11-12 лет'), ('12-13 лет', '12-13 лет'), ('13-14 лет', '13-14 лет'), ('14-15 лет', '14-15 лет'), ('15-16 лет', '15-16 лет')], max_length=10)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.type', verbose_name='Тип одежды')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
